import { BrandProfile } from "@/lib/schema/brand";

export const PRECONFIGURED_BRANDS: (BrandProfile & { id: string })[] = [
  {
    id: "vagabond-travel",
    name: "Vagabond Travel Agency",
    industry: "Travel & Hospitality",
    description: "Bespoke experiential travel agency specializing in immersive, culturally rich journeys across India and Asia.",
    positioning: "Premium editorial travel with human storytelling.",
    target_audience: "Aspirational millennial travelers, luxury experience seekers, cultural enthusiasts.",
    social_handle: "@vagabondtravel",
    visual_identity: {
      logo_variants: ["full-logo-dark", "icon-mark-terracotta"],
      primary_colors: ["#181816", "#FAF9F5"],
      secondary_colors: ["#D97757", "#7BA7D7", "#87A96B"],
      fonts: {
        heading: "Playfair Display",
        body: "Plus Jakarta Sans",
        serif: "Playfair Display",
      },
      typography_rules: ["Subtle, clean text overlay", "High contrast on images"],
      photography_style: "Cinematic editorial travel photography, golden hour lighting, authentic human moments.",
      graphic_style: "Restrained, minimal, high-end editorial composition.",
      image_preferences: ["Warm earth tones", "Subtle landscape compositions", "Human element in frame"],
    },
    voice: {
      tone: "Inspiring, sophisticated, authentic, adventurous",
      vocabulary: ["Journey", "Freedom", "Immersive", "Discovery", "Horizon"],
      sentence_style: "Poetic yet concise opening hooks followed by clear trip details.",
      cta_style: "Subtle invitation to explore",
      forbidden_phrases: ["Cheap deals", "Discount blowout", "Hurry before it's gone!"],
      preferred_phrases: ["Craft your journey", "Discover the unseen"],
    },
    learned_preferences: {
      preferred_visual_styles: [{ value: "editorial_travel", confidence: 0.9, evidence_count: 8, source: "selection_pattern" }],
      preferred_compositions: [{ value: "rule_of_thirds_landscape", confidence: 0.85, evidence_count: 5, source: "selection_pattern" }],
      preferred_hooks: [],
      preferred_caption_styles: [{ value: "storytelling_first", confidence: 0.9, evidence_count: 6, source: "explicit_feedback" }],
      logo_prominence: { value: "subtle_bottom_corner", confidence: 0.95, evidence_count: 6, source: "explicit_feedback" },
      color_preferences: [],
      archetype_affinity: {
        editorial_magazine: 0.92,
        conceptual_split: 0.6,
        comparison_split: 0.4,
        vintage_poster: 0.75,
        saas_dotgrid: 0.25,
      },
      typography_density_preference: "minimalist_punchy",
      visual_temperature_preference: "warm_golden",
    },
  },
  {
    id: "cafe-vagabond",
    name: "Café Vagabond & Roastery",
    industry: "Artisanal Food & Beverage",
    description: "Specialty micro-batch coffee roastery and Scandinavian cafe.",
    positioning: "Slow living, organic origins, quiet luxury coffee.",
    target_audience: "Design conscious coffee connoisseurs, urban creatives.",
    social_handle: "@cafevagabond",
    visual_identity: {
      logo_variants: ["monogram-terracotta"],
      primary_colors: ["#21211F", "#FAF7EE"],
      secondary_colors: ["#D97757", "#2B160E", "#C49A45"],
      fonts: {
        heading: "Outfit",
        body: "Plus Jakarta Sans",
        serif: "Georgia",
      },
      typography_rules: ["Neo-vintage stamps", "Warm organic contrast"],
      photography_style: "Warm espresso tones, top-down artisanal table spreads, tactile steam.",
      graphic_style: "Organic neo-vintage poster aesthetic.",
      image_preferences: ["Espresso tones", "Rustic ceramic mugs", "Morning shadows"],
    },
    voice: {
      tone: "Warm, grounding, tactile, artisanal",
      vocabulary: ["Roast", "Velvety", "Origin", "Ritual", "Harvest"],
      sentence_style: "Sensory evocative phrases celebrating morning rituals.",
      cta_style: "Warm invitation to sip and stay",
      forbidden_phrases: ["Mass-market", "Instant coffee", "Caffeine rush"],
      preferred_phrases: ["Brewed slow", "Crafted daily"],
    },
    learned_preferences: {
      preferred_visual_styles: [],
      preferred_compositions: [],
      preferred_hooks: [],
      preferred_caption_styles: [],
      logo_prominence: { value: "vintage_stamp", confidence: 0.9, evidence_count: 4, source: "selection_pattern" },
      color_preferences: [],
      archetype_affinity: {
        editorial_magazine: 0.8,
        conceptual_split: 0.35,
        comparison_split: 0.3,
        vintage_poster: 0.95,
        saas_dotgrid: 0.1,
      },
      typography_density_preference: "balanced",
      visual_temperature_preference: "warm_golden",
    },
  },
  {
    id: "sapphire-cloud",
    name: "Sapphire Cloud & Labs",
    industry: "Software & Technology",
    description: "Developer platform for multi-agent autonomous creative workflows and real-time canvas rendering.",
    positioning: "Next-generation generative AI infrastructure with zero-latency.",
    target_audience: "CTOs, design engineers, growth marketers, tech founders.",
    social_handle: "@sapphirecloud",
    visual_identity: {
      logo_variants: ["matrix-blue"],
      primary_colors: ["#0F172A", "#F8FAFC"],
      secondary_colors: ["#7BA7D7", "#D97757", "#38BDF8"],
      fonts: {
        heading: "Plus Jakarta Sans",
        body: "Inter",
        serif: "Inter",
      },
      typography_rules: ["Clean micro-chrome", "Monospace stats"],
      photography_style: "Dark slate 3D card stacks, glowing matrix accents, architectural micro-details.",
      graphic_style: "SaaS dot-grid interface chrome.",
      image_preferences: ["Dark slate backdrops", "Floating UI modules", "Clean vector geometry"],
    },
    voice: {
      tone: "Sharp, authoritative, technical, visionary",
      vocabulary: ["Autonomous", "Orchestration", "Scale", "Latency", "Infrastructure"],
      sentence_style: "Direct value proposition with benchmark metrics.",
      cta_style: "Direct developer action",
      forbidden_phrases: ["Magic AI", "Effortless buttons"],
      preferred_phrases: ["Deploy in seconds", "Precision architecture"],
    },
    learned_preferences: {
      preferred_visual_styles: [],
      preferred_compositions: [],
      preferred_hooks: [],
      preferred_caption_styles: [],
      logo_prominence: { value: "top_capsule", confidence: 0.9, evidence_count: 5, source: "selection_pattern" },
      color_preferences: [],
      archetype_affinity: {
        editorial_magazine: 0.3,
        conceptual_split: 0.88,
        comparison_split: 0.82,
        vintage_poster: 0.15,
        saas_dotgrid: 0.95,
      },
      typography_density_preference: "detailed_value_props",
      visual_temperature_preference: "cool_dark",
    },
  },
  {
    id: "aura-botanicals",
    name: "Aura Botanicals & Rituals",
    industry: "Health & Organic Wellness",
    description: "Holistic herbal remedies, cold-pressed botanical essences, and mindful daily rituals.",
    positioning: "Purity of nature formulated for modern calm.",
    target_audience: "Wellness enthusiasts, organic lifestyle practitioners.",
    social_handle: "@aurabotanicals",
    visual_identity: {
      logo_variants: ["leaf-crest"],
      primary_colors: ["#1E4D2B", "#FAF7EE"],
      secondary_colors: ["#87A96B", "#D97757", "#E9D8A6"],
      fonts: {
        heading: "Outfit",
        body: "Plus Jakarta Sans",
        serif: "Playfair Display",
      },
      typography_rules: ["Clean botanical badges", "Subtle organic borders"],
      photography_style: "Soft natural overcast lighting, dewy botanical textures, minimal glass droppers.",
      graphic_style: "Clean neo-vintage organic poster with botanical stamps.",
      image_preferences: ["Earthy green palettes", "Natural sunlight", "Dewdrops on leaves"],
    },
    voice: {
      tone: "Gentle, serene, scientifically grounded, nurturing",
      vocabulary: ["Botanical", "Essence", "Ritual", "Restoration", "Purity"],
      sentence_style: "Calming cadence focusing on self-care rituals.",
      cta_style: "Gentle invitation to restore",
      forbidden_phrases: ["Miracle cure", "Quick fix"],
      preferred_phrases: ["Daily restorative ritual", "Pure organic harvest"],
    },
    learned_preferences: {
      preferred_visual_styles: [],
      preferred_compositions: [],
      preferred_hooks: [],
      preferred_caption_styles: [],
      logo_prominence: { value: "subtle_badge", confidence: 0.88, evidence_count: 4, source: "selection_pattern" },
      color_preferences: [],
      archetype_affinity: {
        editorial_magazine: 0.85,
        conceptual_split: 0.4,
        comparison_split: 0.5,
        vintage_poster: 0.92,
        saas_dotgrid: 0.1,
      },
      typography_density_preference: "minimalist_punchy",
      visual_temperature_preference: "neutral_studio",
    },
  },
];
